# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  test:
    name: Test Gradle
    strategy:
      matrix:
        java: [ 11, 16, 17, 18 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@356abb47e7664b5505e25d7997a5a522a17c62d9
        with:
          arguments: |
            test
            --scan
  javadoc:
    name: Test Javadoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
            ref: ${{github.event.pull_request.head.sha}}
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
            java-version: 18
            distribution: 'temurin'
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Build Javadoc with Gradle
        uses: gradle/gradle-build-action@356abb47e7664b5505e25d7997a5a522a17c62d9
        with:
          arguments: |
            javadoc
            --scan
  codeql-analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Auto-Build
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  tests-complete:
    name: Tests Complete
    needs:
      - test
      - codeql-analyze
      - javadoc
    runs-on: ubuntu-latest
    steps:
      - name: Indicates Tests are Complete
        run: echo Tests Complete
