# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        java: [ 11, 16, 17, 18 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        name: "Checkout Repository"
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
  javadoc:
    name: Javadocs
    needs: build
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
      - uses: actions/setup-java@v3
        name: Set up Java JDK
        with:
          java-version: 18
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Javadoc with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: javadoc
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./build/docs/javadoc
  build-indicator:
    name: Build Indicator
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Indicate Build Complete
        run: echo "Tests Complete"