name: Release
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:



jobs:
  test:
    name: Test Gradle
    strategy:
      matrix:
        java: [ 11, 16, 17, 18 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test
  javadoc:
    name: Test Javadoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
            ref: ${{github.event.pull_request.head.sha}}
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
            java-version: 18
            distribution: 'temurin'
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Build Javadoc with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: javadoc
  release:
    needs:
    - javadoc
    - test
    if: github.repository == 'LittleTealeaf/JavaMarkdown'
    name: Release Next Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Release using Python Script
        run: python .github/python/release.py
        env:
          GITHUB_TOKEN: ${{secrets.PAT}}
